#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sandelys1
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Database1")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertPreke(Preke instance);
    partial void UpdatePreke(Preke instance);
    partial void DeletePreke(Preke instance);
    partial void InsertVieta(Vieta instance);
    partial void UpdateVieta(Vieta instance);
    partial void DeleteVieta(Vieta instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::Sandelys1.Properties.Settings.Default.Database1ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Preke> Prekes
		{
			get
			{
				return this.GetTable<Preke>();
			}
		}
		
		public System.Data.Linq.Table<Vieta> Vietas
		{
			get
			{
				return this.GetTable<Vieta>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Prekes")]
	public partial class Preke : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Name;
		
		private string _Gabaritai;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnGabaritaiChanging(string value);
    partial void OnGabaritaiChanged();
    #endregion
		
		public Preke()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gabaritai", DbType="NVarChar(MAX)")]
		public string Gabaritai
		{
			get
			{
				return this._Gabaritai;
			}
			set
			{
				if ((this._Gabaritai != value))
				{
					this.OnGabaritaiChanging(value);
					this.SendPropertyChanging();
					this._Gabaritai = value;
					this.SendPropertyChanged("Gabaritai");
					this.OnGabaritaiChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Vieta")]
	public partial class Vieta : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _VietosPavadinimas;
		
		private int _Aukstas;
		
		private int _Kiekis;
		
		private string _PrekesPavadinimas;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnVietosPavadinimasChanging(string value);
    partial void OnVietosPavadinimasChanged();
    partial void OnAukstasChanging(int value);
    partial void OnAukstasChanged();
    partial void OnKiekisChanging(int value);
    partial void OnKiekisChanged();
    partial void OnPrekesPavadinimasChanging(string value);
    partial void OnPrekesPavadinimasChanged();
    #endregion
		
		public Vieta()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VietosPavadinimas", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string VietosPavadinimas
		{
			get
			{
				return this._VietosPavadinimas;
			}
			set
			{
				if ((this._VietosPavadinimas != value))
				{
					this.OnVietosPavadinimasChanging(value);
					this.SendPropertyChanging();
					this._VietosPavadinimas = value;
					this.SendPropertyChanged("VietosPavadinimas");
					this.OnVietosPavadinimasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Aukstas", DbType="Int NOT NULL")]
		public int Aukstas
		{
			get
			{
				return this._Aukstas;
			}
			set
			{
				if ((this._Aukstas != value))
				{
					this.OnAukstasChanging(value);
					this.SendPropertyChanging();
					this._Aukstas = value;
					this.SendPropertyChanged("Aukstas");
					this.OnAukstasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kiekis", DbType="Int NOT NULL")]
		public int Kiekis
		{
			get
			{
				return this._Kiekis;
			}
			set
			{
				if ((this._Kiekis != value))
				{
					this.OnKiekisChanging(value);
					this.SendPropertyChanging();
					this._Kiekis = value;
					this.SendPropertyChanged("Kiekis");
					this.OnKiekisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrekesPavadinimas", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string PrekesPavadinimas
		{
			get
			{
				return this._PrekesPavadinimas;
			}
			set
			{
				if ((this._PrekesPavadinimas != value))
				{
					this.OnPrekesPavadinimasChanging(value);
					this.SendPropertyChanging();
					this._PrekesPavadinimas = value;
					this.SendPropertyChanged("PrekesPavadinimas");
					this.OnPrekesPavadinimasChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
